server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: redis-demo
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 1 # 连接池中的最小空闲连接
      shutdown-timeout: 3000 # 连接超时时间（毫秒）